#!/usr/bin/env node
/**
 * Interactive helper to create a minimal `.env` for bootstrap (SQLite path, TLS, first apex list, secrets).
 * Detailed tunables belong in SQLite via the Settings page (`/settings.html`) or `PUT /api/v1/settings`.
 *
 * Run: `npm run setup:env` or `node scripts/setup-env.mjs`
 *
 * Options:
 *   --dry-run   Print the file to stdout instead of writing
 *   --help      Show usage
 */

import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");

function parseArgs(argv) {
    const dryRun = argv.includes("--dry-run");
    const help = argv.includes("--help") || argv.includes("-h");
    return { dryRun, help };
}

function usage() {
    console.log(`Usage: node scripts/setup-env.mjs [options]

Creates a minimal .env in the project root (or prints with --dry-run).
Most settings are stored in SQLite (Settings UI at /settings.html).

Options:
  --dry-run   Write to stdout only; does not create or overwrite .env
  --help, -h  Show this message
`);
}

function randomSecret() {
    return randomBytes(32).toString("base64url");
}

function trimOrEmpty(s) {
    return String(s ?? "").trim();
}

function buildEnvDocument({ isoNow, sqlitePath, tlsCertDir, rootDomains, sessionSecret, registrationSecret }) {
    const lines = [];
    lines.push(`# Generated by scripts/setup-env.mjs (${isoNow})`);
    lines.push(`# Bootstrap only. Edit tunables in the Settings page or SQLite meta.server_settings.`);
    lines.push("");
    lines.push("# --- Required for first start ---");
    lines.push(`SQLITE_DB_PATH=${sqlitePath}`);
    lines.push(`TLS_CERT_DIR=${tlsCertDir}`);
    lines.push("");
    lines.push("# Apex list until you save domains in the management UI (SQLite overrides this).");
    lines.push(`ROOT_DOMAINS=${rootDomains}`);
    lines.push("");
    lines.push("# Session signing for express-easy-auth (override or move to Settings → SQLite).");
    lines.push(`MANAGEMENT_SESSION_SECRET=${sessionSecret}`);
    lines.push("");
    if (registrationSecret) {
        lines.push("# Invite secret for POST /api/v1/auth/register (also configurable in Settings).");
        lines.push(`MANAGEMENT_REGISTRATION_SECRET=${registrationSecret}`);
    } else {
        lines.push("# MANAGEMENT_REGISTRATION_SECRET=<set in Settings or uncomment>");
    }
    lines.push("");
    lines.push("# --- Optional: see .env.example ---");
    return lines.join("\n") + "\n";
}

async function main() {
    const argv = process.argv.slice(2);
    const { dryRun, help } = parseArgs(argv);
    if (help) {
        usage();
        process.exit(0);
    }

    const rl = readline.createInterface({ input, output });

    try {
        console.log("");
        console.log("Reverse proxy — minimal .env bootstrap");
        console.log("Press Enter for [defaults]. Other settings: use /settings.html after the server runs.");
        console.log("");

        const outPath = join(REPO_ROOT, ".env");
        if (!dryRun && existsSync(outPath)) {
            const ow = trimOrEmpty(await rl.question(`.env already exists. Overwrite? [y/N]: `));
            if (ow.toLowerCase() !== "y" && ow.toLowerCase() !== "yes") {
                console.log("Aborted.");
                process.exit(0);
            }
        }

        const sqlitePath =
            trimOrEmpty(await rl.question("SQLite database path [./reverse-proxy.db]: ")) || "./reverse-proxy.db";

        let tlsCertDir = trimOrEmpty(
            await rl.question("TLS certificate directory (e.g. /etc/letsencrypt/live/your-domain.com): ")
        );
        while (!tlsCertDir) {
            tlsCertDir = trimOrEmpty(await rl.question("TLS_CERT_DIR is required: "));
        }

        let primary = trimOrEmpty(await rl.question("Primary apex domain (e.g. example.com): "));
        while (!primary) {
            primary = trimOrEmpty(await rl.question("Primary apex domain: "));
        }
        const more = trimOrEmpty(await rl.question("Additional apex domains, comma-separated (or empty): "));
        const rootDomains = more ? `${primary},${more.split(",").map(s => s.trim()).filter(Boolean).join(",")}` : primary;

        const genSessAns = trimOrEmpty(await rl.question("Generate MANAGEMENT_SESSION_SECRET? [Y/n]: ")).toLowerCase();
        const genSess = genSessAns !== "n" && genSessAns !== "no";
        let sessionSecret;
        if (genSess) {
            sessionSecret = randomSecret();
        } else {
            sessionSecret = trimOrEmpty(await rl.question("Paste MANAGEMENT_SESSION_SECRET: "));
            if (!sessionSecret) {
                console.log("Generating session secret.");
                sessionSecret = randomSecret();
            }
        }

        let registrationSecret = "";
        const reg = trimOrEmpty(await rl.question("Set MANAGEMENT_REGISTRATION_SECRET now? [y/N]: "));
        if (reg.toLowerCase() === "y" || reg.toLowerCase() === "yes") {
            const g = trimOrEmpty(await rl.question("Generate random invite secret? [Y/n]: ")).toLowerCase() !== "n";
            registrationSecret = g ? randomSecret() : trimOrEmpty(await rl.question("Paste invite secret: "));
            if (!registrationSecret) registrationSecret = randomSecret();
        }

        const isoNow = new Date().toISOString();
        const doc = buildEnvDocument({
            isoNow,
            sqlitePath,
            tlsCertDir,
            rootDomains,
            sessionSecret,
            registrationSecret
        });

        if (dryRun) {
            console.log(doc);
        } else {
            writeFileSync(outPath, doc, "utf8");
            console.log("");
            console.log(`Wrote ${outPath}`);
            console.log("Start the server, then open /settings.html to tune management port, WebAuthn, trust proxy, rate limits, and more (stored in SQLite).");
        }
    } finally {
        rl.close();
    }
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
